site_name: Litmus Experiments
theme: 
  name: material
  palette:
    primary: blue
  font:
    text: Work Sans
  highlightjs: true
  logo: assets/litmus.png
  hljs_languages:
    - yaml
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true
nav:
    - Home: resources/index.md
    - AWS: 
        - resources/ebs-loss.md
        - resources/ec2-stop.md
    - AKS:
        - resources/aks-stop.md
    - GCP:
        - Instance Stop: resources/gcp-stop.md
    - Pod:
        - Pod Delete: resources/pod-delete.md
    - Node:
        - Node Restart: resources/node-restart.md