site_name: Litmus Experiments
theme: 
  name: readthedocs
  highlightjs: true
  hljs_languages:
        - yaml
nav:
    - Home: index.md
    - AWS: 
      - EBS Loss: ebs-loss.md
      - EC2 Stop: ec2-stop.md
    - AKS:
      - instance:
        - Instance Stop: aks-stop.md
    - GCP:
      - Instance Stop: gcp-stop.md
    - Pod:
      - Pod Delete: pod-delete.md
    - Node:
      - Node Restart: node-restart.md